name: Forge test

on:
  pull_request:
  push:
    branches:
      - main
      - evm
      - release/**

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false   # 👈 stop fetching submodules

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --evm-version=prague

      - name: Run Forge tests
        run: |
          forge test -vvv --evm-version=prague

      - name: Run Go slinky tests (if present)
        run: |
          set -euo pipefail
          if [ -d "./x/slinky" ]; then
            go test ./x/slinky/...
          else
            echo "No Slinky module found. Skipping tests."
          fi
